### ISSUE TITLE
gdimagecopyresampled/bug00201 fails on some arch

### ISSUE THREAD

**Issue by remicollet** [libgd/libgd#364]
Ok on i386, x86_64, armv7hl
Fails on ppc64, ppc64le, aarch64

(probably, yet another rouding issue)

**Comment by cmb69** [comment]
Can you please post the _out and _diff images and the log entry?

**Comment by remicollet** [comment]
Not easily, I need a real computer (these build are run in Fedora infra, and I don't have access to the build tree)

**Comment by oerdnj** [comment]
I have an access to porter boxes on Debian, but it seems that Debian is ok on all archs: https://buildd.debian.org/status/package.php?p=libgd2

Perhaps again related to the underlying libraries versions?

**Comment by remicollet** [comment]
Fixed by b7b66ea1ea9191b5bf1c2fdc9c7915c9ba69c4bb (don't know why this wasn't applied in 2.2...)

**Comment by rainer-tammer** [comment]
Hello,
This test still fails on AIX 7.2 (ppc64):

FAIL: gdimagecopyresampled/bug00201

# gdimagecopyresampled/bug00201;echo $?
gdimagecopyresampled/bug00201.c:68: Total pixels changed: 199 with a maximum channel difference of 255.
1

Bye
  Rainer

**Comment by pierrejoye** [comment]
@rainer-tammer I don't have PPC64 to test sadly

**Comment by pierrejoye** [comment]
@remicollet would it be possible to run the gh action runner on this PPC64? ARM is covered now (Graviton/Neon)

**Comment by pierrejoye** [comment]
I filled a request at OSUSL initiative, let see. Power9. That could help :)

**Comment by vapier** [comment]
i might be able to get you an acct on a Gentoo box.  hopefully i'll have info in the next week.

if it comes up, i can get you access to an s390 system at any time.

**Comment by pierrejoye** [comment]
@vapier excellent! Thank you!

I can then add the github action bots on it and we will have it as part of our CI :)

**Comment by pierrejoye** [comment]
some of the issues on aarch64, for what I see are:

1. use of char as an intel char while it is unsigned on aarch64
2. rely on non supported (by C standard) of float to int/char cast
3. and some floating ops, but those are easy to fix I think

**Comment by vapier** [comment]
i don't think we can use it for hosting GH actions.  i meant more as a dev box for you to debug reports and experiment and such.

**Comment by pierrejoye** [comment]
that's already very good then :).

especially for the standard floating to int/chat and other fp modes.

**Comment by pierrejoye** [comment]
Thanks to openpower@unicamp, it looks like we will have  a ppc64 for debugging and ci soon, just got the credentials

**Comment by rainer-tammer** [comment]
Hello,
I can run some tests on AIX 7.2 / 7.1. 

Currently there is unfortunately no direct access from the Internet.
I might be able to setup a AIX 7.1 LPAR in needed. I could provide limited access to this LPAR.

Bye
  Rainer

**Comment by pierrejoye** [comment]
Hi Rainer

thank you  :))

As far as I can see, the gh agent pull the jobs from gh and does not need
to be accessible from internet. Is it something that could be done?
